//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobMatch
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FindJobDBEntities : DbContext
    {
        public FindJobDBEntities()
            : base("name=FindJobDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employer> Employer { get; set; }
        public virtual DbSet<EmployerRates> EmployerRates { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<JobSeeker> JobSeeker { get; set; }
        public virtual DbSet<JobSeekerRates> JobSeekerRates { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<RequiredSkill> RequiredSkill { get; set; }
        public virtual DbSet<Skill> Skill { get; set; }
    }
}
